- name: Installing
  hosts: participantCluster
  tasks:
    - name: Show all the hosts in the inventory
      debug:
        msg: " peer_ipv4 = {{ item.value.ip_v4 if (ansible_hostname != item.value.fqdn) else item.value.ip_v4 }}"
      loop: "{{ lookup('dict', node) }}"  
      when: "{{ item.value.fqdn != ansible_hostname }}"
    - name: "Config Seesaw"
      template: src=seesaw.cfg dest=/etc/seesaw/seesaw.cfg
    - name: Inserting a line after a pattern in Ansible example 
      loop: "{{ lookup('dict', node) }}"  
      when: "{{ item.value.fqdn != ansible_hostname }}"
      lineinfile:
        path: /etc/seesaw/seesaw.cfg
        line: peer_ipv4 = {{ item.value.ip_v4 if (ansible_hostname != item.value.fqdn) else item.value.ip_v4 }}
        insertafter: node_ipv4.*      

